<footer>
    <div class="wrapper">
        <h4>Andrew Holloway &copy; <?php echo DATE('Y') ?></h4>
        <p>Proudly <u>not</u> generated by ChatGPT</p>
        <div id="footlinks">
            <a tabindex="0" href="/sitemap.txt">site map</a>
            <a tabindex="0" href="mailto:site@andrewholloway.info">contact</a>
        </div>
    </div>
</footer>
<?php mysqli_close($conn); ?>